services:
#mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/zderfouf/mariadb
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception