events {}

http {
    include         /etc/nginx/mime.types;
    default_type    application/octet-stream;

    server {
        listen 443 ssl;
        server_name         64.227.114.92 zderfouf.42.fr;
        ssl_certificate     /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        index index.php;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}
# docker compose down --rmi all -v